### ISSUE TITLE
Encoded flacs seem to only play about half way before halting. They don't play at all using QT Player.

### ISSUE THREAD

**Issue by dtzxporter** [yotarok/flacenc-rs#195]
Either using my custom implementation of flacenc or the provided CLI, the resulting flac file only plays about half way (when testing through chrome) and when testing in Quicktime Player no audio plays period (but the duration is correct).

(Of course, I tested other flac files from samples online, they all play as expected.)

Purely testing against PCM16 wavs at the moment.

Here is the source / sample:

[broken.zip](https://github.com/user-attachments/files/16449158/broken.zip)

**Comment by dtzxporter** [comment]
Oddly enough, ffmpeg can decode it back to the same wav and it will play fully. Must be something ffmpeg ignores...

**Comment by yotarok** [comment]
Hi, thanks for the report.  I will take a look.
At least, I could reproduce the issue on my macbook.
(I'm on vacation right now, so may be slow to respond though)

**Comment by yotarok** [comment]
Okay, I think I found the root cause of this issue.

QuickTime doesn't allow FLAC frames that do not contain sampling-rate specifications.
FLAC allows defining it in the stream header instead of each frame header, and flacenc-rs is relying on that feature.
However, as mentioned in [[https://xiph.org/flac/format.html]] cited below,

> Again, since a decoder may start decoding at an arbitrary frame in the stream, each frame header must contain some basic information about the stream because the decoder may not have access to the STREAMINFO metadata block at the start of the stream.

it sounds better to have sampling rates in the frames, and in the case with QuickTime player, apparently it is mandatory.

I'll implement a fix and make it a default behavior of the encoder.

**Comment by dtzxporter** [comment]
Great! Thanks for looking into it.
